channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - h5py>=3.10
  - matplotlib
  - simpleitk>=2.3
  - hdf5storage
  - scikit-image
  - numba
  - pandas
  - pymaxflow
  - opencv
  - nibabel
  - pydicom
  - pip
  - pip:
    - git+https://github.com/BMRRgroup/2echo-WaterFat-hmrGC.git
